### ISSUE TITLE
[FEAT] Supabase 설치 및 Auth 기능 

### ISSUE THREAD

**Issue by chyerin802** [chyerin802/Clip-Pin#2]
## About
로그인/회원가입 기능 구현을 위한 Supabase 설치 및 Auth 기능 연동

## Todo
- [ ] Supabase install & Setting
- [ ] 로그인 및 회원가입 기능 check
- [ ] 구글 로그인 기능 check

### Docs & Links
https://supabase.com/docs/guides/auth
